name: Staging Deployment via Dispatch

on:
  repository_dispatch:
    types: [deploy-staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment..."
          # Your deployment script or commands go here
          echo "model_s3_url: ${{ github.event.client_payload.model_s3_url }}"

      - name: Set Model S3 URL
        run: |
          sed -i 's|value: "s3://[^"]*"|value: "${{ github.event.client_payload.model_s3_url }}"|' argocd/argo-rollout.yml
          cat argocd/argo-rollout.yml

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deployment-artifact
          path: argocd/argo-rollout.yml  # Update this path to the directory containing your modified files

  update-files:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: deployment-artifact
          path: ./downloaded-artifact

      - name: List Files in Downloaded Artifact
        run: |
          find ./downloaded-artifact

      - name: Update Model S3 URL
        run: |
          sed -i 's|value: "s3://[^"]*"|value: "${{ github.event.client_payload.model_s3_url }}"|' ./downloaded-artifact/argocd/argo-rollout.yml
          cat ./downloaded-artifact/argocd/argo-rollout.yml

      - name: Upload Updated Artifact
        uses: actions/upload-artifact@v2
        with:
          name: updated-deployment-artifact
          path: ./downloaded-artifact
