name: Staging Deployment via Dispatch
##

on:
  repository_dispatch:
    types: [deploy-staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment..."
          # Your deployment script or commands go here
          echo "model_s3_url: ${{ github.event.client_payload.model_s3_url }}"
  
      - name: Set Model S3 URL
        run: |
          git checkout -b test
          sed -i 's|value: "s3://[^"]*"|value: "${{ github.event.client_payload.model_s3_url }}"|' argocd/argo-rollout.yml
          cat argocd/argo-rollout.yml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: Update S3 URL
