name: Staging Deployment via Dispatch

on:
  repository_dispatch:
    types: [deploy-staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment..."
          # Your deployment script or commands go here
          echo "model_s3_url: ${{ github.event.client_payload.model_s3_url }}"
  
      - name: Set Model S3 URL
        run: |
          sed -i 's|value: "s3://[^"]*"|value: "${{ github.event.client_payload.model_s3_url }}"|' argocd/argo-rollout.yml
          cat argocd/argo-rollout.yml

      - name: Commit and Push Changes
        run: |
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
          git add argocd/argo-rollout.yml
          git commit -m "Update model_s3_url in argo-rollout.yml"
          git push origin test --force
          
          # git config -- user.email "jspawar80@gmail.com"
          # git config --global user.name "jspawar80"
          # git checkout -b test
          # git add argocd/argo-rollout.yml
          # git commit -m "Update model_s3_url in argo-rollout.yml"

          # Force push changes to the remote branch
          git push origin test --force
          
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deployment-artifact
          path: argocd/argo-rollout.yml
