name: Staging Deployment via Dispatch

on:
  repository_dispatch:
    types: [stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment..."
          # Your deployment script or commands go here
          echo "model_s3_url: ${{ github.event.client_payload.model_s3_url }}"
  
      - name: Update Model Version in the kustomization.yaml
        uses: fjogeleit/yaml-update-action@main
        env:
          IMAGE_TAG: ${{github.event.client_payload.model_s3_url}}
        with:
          valueFile: "argocd/argo-rollout.yml"
          value: model_s3_url=${{ env.IMAGE_TAG }}
          propertyPath: configMapGenerator[0].literals[0]
          branch: main
          targetBranch: main
          createPR: false
          masterBranchName: main
          message: 'Update Image Version to ${{ env.IMAGE_TAG }}' 

      - name: Echo the updated file
        run: cat argocd/argo-rollout.yml
